publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "images"
editor:
  preview: false
backend:
  name: git-gateway
  branch: main
collections:
  - name: "static"
    label: "Páginas estáticas"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/content/index.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }