publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "images"
editor:
  preview: false
backend:
  name: git-gateway
  branch: main
collections:
  - name: "static"
    label: "Páginas estáticas"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/content/index.md"
        fields:
          - label: "Secciones"
            name: "sections"
            widget: "list"
            allow_add: true
            types:
              - label: "Slider de imágenes"
                name: "slider"
                fields:
                  - name: "Slide"
                    label: "Contenido"
                    widget: "list"
                    summary: "{{fields.title}}"
                    allow_add: true
                    fields:
                      - { label: Imagen o video, name: media, widget: file, hint: Tamaño recomendado 1440x1024 o superior, required: false }
                      - { label: Título, name: title, widget: string, hint: Título sobre el video/imagen, required: false }
                      - { label: Descripción, name: description, widget: text, hint: Descripción sobre el video/imagen, required: false }
                      - label: "Esquema de color"
                        name: "colorScheme"
                        widget: "select"
                        required: false
                        hint: Determina los colores a utilizar para el fondo, el texto y los botones. Si no se completa, se usará el verde claro por defecto.
                        options:
                          - { label: "Verde claro", value: "primary", hint: "Color de título y botón verde claro, color de texto blanco" }
                          - { label: "Verde oscuro", value: "dark", hint: "Color de todos los elementos verde oscuro" }
                          - { label: "Amarillo", value: "secondary", hint: "Color de todos los elementos verde oscuro" }
                          - { label: "Blanco", value: "light", hint: "Color de fondo blanco, color de texto verde oscuro, color de botón verde claro"  }
                      - { label: Decoraciones, name: decorations, widget: boolean, hint: Muestra u oculta la grilla decorativa de puntos, default: true, required: false }
                      - label: "Botones"
                        name: "ctas"
                        widget: "list"
                        allow_add: true
                        max: 2
                        hint: Los botones que se muestran debajo del texto. Si no se completan, no se mostrarán botones.
                        fields:
                          - { label: Texto del botón, name: text, widget: string, hint: "Si no se completa, el texto por defecto será 'Conocé más'", required: false }
                          - { label: URL del botón, name: link, widget: string, hint: La URL a la que direcciona el botón cuando es clickeado }
              - label: "Texto e imagen"
                name: "textAndImage"
                fields:
                  - { label: Imagen, name: image, widget: file, hint: Tamaño recomendado 1024x1024 o superior, required: false }
                  - { label: Título, name: title, widget: string, hint: Título sobre el video/imagen, required: false }
                  - { label: Descripción, name: description, widget: text, hint: Descripción sobre el video/imagen, required: false }
                  - label: "Esquema de color"
                    name: "colorScheme"
                    widget: "select"
                    required: false
                    hint: Determina los colores a utilizar para el fondo, el texto y los botones. Si no se completa, se usará el verde claro por defecto.
                    options:
                      - { label: "Verde claro", value: "primary", hint: "Color de título y botón verde claro, color de texto blanco" }
                      - { label: "Verde oscuro", value: "dark", hint: "Color de todos los elementos verde oscuro" }
                      - { label: "Amarillo", value: "secondary", hint: "Color de todos los elementos verde oscuro" }
                      - { label: "Blanco", value: "light", hint: "Color de fondo blanco, color de texto verde oscuro, color de botón verde claro"  }
                  - label: "Ubicación de la imagen"
                    name: "imagePlacement"
                    widget: "select"
                    required: false
                    hint: Ubica la imagen a la izquierda o a la derecha del texto. Si no se completa, se ubicará a la izquierda por defecto.
                    options:
                      - { label: Izquierda, value: "left", required: false }
                      - { label: Derecha, value: "right", required: false }
                  - { label: Decoraciones, name: decorations, widget: boolean, hint: Muestra u oculta la grilla decorativa de puntos, default: true, required: false }
                  - label: "Botones"
                    name: "ctas"
                    widget: "list"
                    allow_add: true
                    max: 2
                    hint: Los botones que se muestran debajo del texto. Si no se completan, no se mostrarán botones.
                    fields:
                      - { label: Texto del botón, name: text, widget: string, hint: "Si no se completa, el texto por defecto será 'Conocé más'", required: false }
                      - { label: URL del botón, name: link, widget: string, hint: La URL a la que direcciona el botón cuando es clickeado }